In [97]:
import numpy as np 

X = np.ones((5,5))


In [98]:
def compute_integral(img):

    return np.cumsum(np.cumsum(img, axis=0), axis=1)

In [147]:
from skimage.feature  import  haar_like_feature

def compute_feature(ii, y, x, w, h):
    Area = ii[y + h, x + w] - ii[y, x + w] - ii[y + h, x] + ii[y, x]
    return Area

In [411]:
X= np.array([[2,4],[3,5]])
ii = compute_integral(X)
haar_like_feature(X,0,0,X.shape[1],X.shape[0],feature_type="type-2-x")

array([ 0, -1, -1])

In [428]:
A = np.array([[154,21,254,198],[67,58,20,208],[167,233,113,222]])
ii_ = compute_integral(A)
haar_like_feature((ii_),0,0,ii_.shape[1],ii_.shape[0],feature_type="type-2-x")

array([-133,  277, -142,  380,  -76,  315,  233,  195,   75,  -56,  132,
        241,   -9,  103,   57,   38,  -38, -158,  188,  297,   66,  -65,
       -120,  109])

In [493]:
from skimage.feature  import  haar_like_feature

def compute_feature(ii, y, x, w, h):
        BR = ii[y+h,x+w]
        TL = ii[y-1,x-1] if y>0 and x>0 else 0 
        TR = ii[y-1,x+w] if y>0 else 0 
        BL = ii[y+h,x-1] if x>0 else 0 

        return BR + TL - TR-BL
    

def compute_2rec(X):
    features = [] 
    print("hallo")

    height,width = X.shape
    n = 0
    for w in range(0,height):
        for h in range(0,width):

            y = 0 
            while(h+y-1<X.shape[0]):
                x = 0 
                while(x+2*h <X.shape[1]):
                    
                    right = compute_feature(X,y+h,x+w,w,h)
                    left = compute_feature(X,y,w+2*x,w,h)

                    features.append(right-left)
                    x+=1
                y+=1


    return features
h = compute_2rec(ii)

hallo


IndexError: index 2 is out of bounds for axis 1 with size 2

In [488]:
h

[0, 0, 0, 0, 0, 0]

In [369]:
hh = haar_like_feature(X,0,0,ii.shape[1],ii.shape[0],feature_type="type-2-x")
hhh  = haar_like_feature(X,0,0,ii.shape[1],ii.shape[0],feature_type="type-2-y")
print(hh,hhh)

[ 0 -1 -1] [-1 -3 -2]


In [483]:
def compute_feature(ii, y, x, w, h):
        BR = ii[y+h,x+w]
        TL = ii[y-1,x-1] if y>0 and x>0 else 0 
        TR = ii[y-1,x+w] if y>0 else 0 
        BL = ii[y+h,x-1] if x>0 else 0 

        return BR + TL - TR-BL
    


315

In [473]:
ii_[0+2]

array([ 388,  700, 1087, 1715])

In [500]:
x = np.array([[1,2,3],[2,4,6],[4,8,12]])

In [497]:
x

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 4,  8, 12]])

In [521]:
tt = compute_integral(x)

In [522]:
tt

array([[ 1,  3,  6],
       [ 3,  9, 18],
       [ 7, 21, 42]])

In [571]:
f = haar_like_feature(tt,0,0,x.shape[1],x.shape[0],feature_type=["type-2-y","type-2-x"])


In [578]:
f

array([ 1,  3,  6,  2,  5,  3,  2,  6, 12,  4, 10,  6,  1,  3,  7,  1,  3,
        7,  2,  6,  2,  6,  4,  4])

In [623]:
matrices = [] 
x = tt 
h = 0
for i in range(0,x.shape[0]):
    for j in range(0,x.shape[1]):
        h = 1
        while(i+h-1<x.shape[1]):
            w = 1 
            while(j+w-1<x.shape[0]):

                if(j+2*w-1<x.shape[0]):
                    left = compute_feature(x,i,j,w,h)
                    right = compute_feature(x,i,j+w,w,h)
                    matrices.append((right-left))
                    
                if(i+2*h-1<x.shape[1]):
                    top = compute_feature(x,i,j,w,h)
                    bottom = compute_feature(x,i+h,j,w,h)
                    matrices.append((bottom-top))
                w+=1
            h+=1 


In [624]:
(sorted(matrices))

[1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 6, 6, 6, 6, 6, 7, 7, 10, 12]

In [625]:
f = haar_like_feature(x,0,0,x.shape[1],x.shape[0],feature_type=["type-2-x","type-2-y"])

sorted(f)

[1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 6, 6, 6, 6, 6, 7, 7, 10, 12]

In [586]:
x

array([[ 1,  3,  6],
       [ 3,  9, 18],
       [ 7, 21, 42]])

In [587]:
tt

array([[ 1,  3,  6],
       [ 3,  9, 18],
       [ 7, 21, 42]])

In [580]:
def compute_feature(ii, y, x, w, h):
        BR = ii[y+h-1,x+w-1] 
        TL = ii[y-1,x-1] if y>0 and x>0 else 0 
        TR = ii[y-1,x+w-1] if y>0 else 0 
        BL = ii[y+h-1,x-1] if x>0 else 0 

        return BR + TL - TR-BL

In [544]:
x[0:0,1]

array([], dtype=int32)